name: Fetch and Showcase Repositories by Topic

on:
  push:
    branches:
      - main

jobs:
  fetch_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch repositories by topic
        id: fetch_repos
        run: |
          # Define the username and topic
          USERNAME='bharatveeryadav'     # Replace with your GitHub username or organization
          TOPIC='devops'                  # Replace with the desired topic (e.g., 'devops', 'cloud', etc.)
          OUTPUT_DIR='projects'               # Directory to clone projects

          # Create output directory
          mkdir -p $OUTPUT_DIR

          # Make the API request to fetch repositories by topic
          response=$(curl -s -H "Authorization: token ${{ secrets.MY_PERSONAL_ACCESS_TOKEN}}" \
            "https://api.github.com/search/repositories?q=user:$USERNAME+topic:$TOPIC&per_page=100")

          # Filter repositories by topic and clone them
          echo "$response" | jq -r '.items[].clone_url' | while read -r repo; do
            # Clone each repository into the output directory
            git clone "$repo" "$OUTPUT_DIR/$(basename $repo .git)"
          done

      - name: Commit and Push Changes
        run: |
          cd $OUTPUT_DIR
          git add .
          git commit -m "Add repositories with topic '$TOPIC'"
          git push origin main

