name: Fetch Repositories with Prefix

on:
  push:
    branches:
      - main

jobs:
  fetch_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch repositories
        id: fetch_repos
        run: |
          USERNAME='bharatveeryadav'  # Change this to your GitHub username or organization
          PREFIX='DevOps-Project'              # Change this to your desired prefix

          response=$(curl -s -H "Authorization: token ${{ secrets.REPO }}" "https://api.github.com/users/$USERNAME/repos")

          # Create or clear README.md
          echo "# My Projects" > README.md
          echo "" >> README.md
          echo "Welcome to my collection of projects! Here are some of my repositories:" >> README.md
          echo "" >> README.md
          echo "## Projects" >> README.md
          echo "" >> README.md

          # Filter repositories by prefix and format the output
          repos=$(echo "$response" | jq -r --arg PREFIX "$PREFIX" '.[] | select(.name | startswith($PREFIX)) | .name')
          
          for repo in $repos; do
            echo "- [$repo](https://github.com/$USERNAME/$repo)" >> README.md
          done

          echo "" >> README.md
          echo "## More Repositories" >> README.md
          echo "" >> README.md
          echo "You can find more of my repositories on my [GitHub profile](https://github.com/$USERNAME)." >> README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "you@example.com" # Replace with your email
          git config --local user.name "Your Name"        # Replace with your name
          git add README.md
          git commit -m "Update README with repositories"
          git push
