name: Fetch Repos with Prefix

on: 
  push:
    branches:
      - main

jobs:
  fetch-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch repositories with prefix
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
      run: |
        PREFIX="FindRepos"
        USERNAME="bharatveeryadav"
        REPOS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/$USERNAME/repos" | jq -r '.[] | select(.name | startswith("'"$PREFIX"'")) | .name')
        echo "Repositories with prefix '$PREFIX':"
        echo "$REPOS"
