name: Fetch Repositories

on: [push]

jobs:
  fetch-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Fetch repositories with prefix
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
        PREFIX: 'FRepo'
      run: |
        response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/${{ github.actor }}/repos")
        echo "$response" | jq -r --arg PREFIX "$PREFIX" '.[] | select(.name | startswith($PREFIX)) | .clone_url' | while read -r repo; do
          git clone "$repo"
        done

    - name: Add current repository
      run: |
        echo "https://github.com/${{ github.repository }}.git" >> repo_list.txt

    - name: Print all repositories
      run: |
        cat repo_list.txt
