name: Fetch Repositories with Prefix

on:
  push:
    branches:
      - main

jobs:
  fetch_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch repositories
        id: fetch_repos
        run: |
          # Define the username and prefix
          USERNAME='bharatveeryadav'  # Change this to your GitHub username or organization
          PREFIX='FindRepos'            # Change this to your desired prefix

          # Make the API request to fetch repositories
          response=$(curl -s -H "Authorization: token ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}" "https://api.github.com/users/$USERNAME/repos")

          # Filter repositories by prefix
          repos=$(echo "$response" | jq -r --arg PREFIX "$PREFIX" '.[] | select(.name | startswith($PREFIX)) | .name')

          # Print the repositories
          echo "Repositories with prefix '$PREFIX':"
          echo "$repos"

          # Optionally, set the output
          echo "::set-output name=repos::$repos"
