name: Fetch and Showcase Repositories

on:
  push:
    branches:
      - main

jobs:
  fetch_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch repositories
        id: fetch_repos
        run: |
          USERNAME='BHARATVEERYADAV'
          PREFIX='DevOps-Project'
          OUTPUT_DIR='projects'
          
          mkdir $OUTPUT_DIR
          
          response=$(curl -s -H "Authorization: token ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}" "https://api.github.com/users/$USERNAME/repos")
          
          echo "$response" | jq -r --arg PREFIX "$PREFIX" '.[] | select(.name | startswith($PREFIX)) | .clone_url' | while read -r repo; do
            git clone "$repo" "$OUTPUT_DIR/$(basename $repo .git)"
          done

      - name: Commit and Push Changes
        run: |
          cd $OUTPUT_DIR
          git add .
          git commit -m "Add project repositories"
          git push origin main
