name: Fetch and Showcase Repositories

on:
  push:
    branches:
      - main

jobs:
  fetch_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch repositories
        id: fetch_repos
        run: |
          # Define the username and prefix
          USERNAME='BHARATVEERYADAV'  # Change this to your GitHub username or organization
          PREFIX='DevOps-Project-1'              # Change this to your desired prefix
          OUTPUT_DIR='projects'              # Directory to clone projects

          # Create output directory
          mkdir $OUTPUT_DIR

          # Make the API request to fetch repositories
          response=$(curl -s -H "Authorization: token ${{ secrets.REPO }}" "https://api.github.com/users/$USERNAME/repos")

          # Filter repositories by prefix and clone them
          echo "$response" | jq -r --arg PREFIX "$PREFIX" '.[] | select(.name | startswith($PREFIX)) | .clone_url' | while read -r repo; do
            # Clone each repository into the output directory
            git clone "$repo" "$OUTPUT_DIR/$(basename $repo .git)"
          done

      - name: Commit and Push Changes
        run: |
          cd $OUTPUT_DIR
          git add .
          git commit -m "Add project repositories"
          git push origin main
