name: Create New Branch

on:
  push:
    branches:
      - main

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKENs }}
        run: |
          # Define variables
          OWNER='bharatveeryadav'  # Change this to your GitHub username or organization
          REPO='DevOps-Project'              # Change this to your repository name
          NEW_BRANCH='new-branch-name'  # Change this to your new branch name
          BASE_BRANCH='main'            # Change this to the base branch name

          # Get the latest commit SHA from the base branch
          BASE_SHA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$OWNER/$REPO/git/refs/heads/$BASE_BRANCH" | jq -r '.object.sha')

          # Create the new branch
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"ref\": \"refs/heads/$NEW_BRANCH\", \"sha\": \"$BASE_SHA\"}" \
            "https://api.github.com/repos/$OWNER/$REPO/git/refs"
